# Generated by Django 5.2.7 on 2025-10-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='conteudo',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_publicacao',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_atualizacao',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='post',
            name='rascunho',
            field=models.BooleanField(default=False, help_text='Se marcado, o post não será exibido publicamente.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Um identificador curto e único para a URL.', max_length=250, unique_for_date='published'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
