# Generated by Django 5.2.7 on 2025-10-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_autor_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rascunho',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='published'),
        ),
    ]
